name: llvmdev_win_builder

on:
  workflow_dispatch:

jobs:

  windows:
    name: Windows
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -elx {0}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""

      - name: Install conda-build
        run: |
          conda install conda-build

      - name: Build
        run: |
          RECIPE_NAME=./conda-recipes/llvmdev_manylinux
          conda build $RECIPE_NAME
          echo "OUTPUT=$(conda build --output $RECIPE_NAME)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvmdev
          path: ${{ env.OUTPUT }}
