name: llvmdev

on:
  pull_request:
    paths:
      - .github/workflows/llvmdev_build.yml
      - buildscripts/github/llvmdev_evaluate.py
      - conda-recipes/llvmdev/**
      - conda-recipes/llvmdev_for_wheel/**
  label:
    types: [created]
  workflow_dispatch:
    inputs:
      platform:
        description: Conda Platform
        default: all
        required: true
        type: choice
        options:
          - all
          - linux-64
          - linux-aarch64
          - linux-s390x
          - osx-64
          - osx-arm64
          - win-64
      recipe:
        description: Recipe to build
        default: all
        required: true
        type: choice
        options:
          - all
          - llvmdev
          - llvmdev_for_wheel
      run_stage:
        description: Multi-stage build control for s390x
        default: all
        required: true
        type: choice
        options:
          - all
          - start
          - continue
          - end

concurrency:
  # Concurrency group that uses the workflow name and PR number if available
  # or commit SHA as a fallback. If a new build is triggered under that
  # concurrency group while a previous build is running it will be canceled.
  # Repeated pushes to a PR will cancel all previous builds, while multiple
  # merges to master will not cancel.
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number
      || toJson(github.event.inputs)
      || github.event.label.name
      || github.sha }}
  cancel-in-progress: true

env:
  ARTIFACT_RETENTION_DAYS: 90

jobs:
  evaluate:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.matrix-eval.outputs.matrix }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Evaluate matrix
        id: matrix-eval
        run: |
          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          python ./buildscripts/github/llvmdev_evaluate.py \
            --event-name workflow_dispatch \
            --platform ${{ github.event.inputs.platform }} \
            --recipe ${{ github.event.inputs.recipe }} \
            --run-stage ${{ github.event.inputs.run_stage }} \
            >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT 

  build-and-test:
    needs: evaluate
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.evaluate.outputs.matrix) }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          lfs: true

      - name: Start s390x build
        if: (matrix.platform == 'linux-s390x' && matrix.recipe == 'llvmdev_for_wheel' && github.event.inputs.run_stage == 'start')
        env:
          CONDA_CHANNEL_DIR: conda_channel_dir
        run: |
          set -x
          # This step will start the podman container and the build.
          # The build is expected to time out, but the container will remain.
          ./buildscripts/manylinux/docker_run_s390x.sh build_llvmdev_start.sh start

      - name: Continue s390x build
        if: (matrix.platform == 'linux-s390x' && matrix.recipe == 'llvmdev_for_wheel' && github.event.inputs.run_stage == 'continue')
        env:
          CONDA_CHANNEL_DIR: conda_channel_dir
        run: |
          set -x
          # This step re-enters the existing container and continues the build.
          ./buildscripts/manylinux/docker_run_s390x.sh build_llvmdev_continue.sh continue

      - name: Finish s390x build and upload
        if: (matrix.platform == 'linux-s390x' && matrix.recipe == 'llvmdev_for_wheel' && github.event.inputs.run_stage == 'end')
        env:
          CONDA_CHANNEL_DIR: conda_channel_dir
        run: |
          set -x
          # This step runs on the host to copy the artifact out of the container
          # and then remove the container.
          mkdir -p "${CONDA_CHANNEL_DIR}"
          podman cp llvm20-s390x:/root/llvmlite/docker_output/ "${CONDA_CHANNEL_DIR}/"
          podman stop llvm20-s390x
          podman rm llvm20-s390x
          
      - name: Create run ID artifact
        if: github.event.inputs.run_stage == 'end' || matrix.platform != 'linux-s390x'
        run: echo ${{ github.run_id }} > run_id.txt
          
      - name: Upload run ID artifact
        if: github.event.inputs.run_stage == 'end' || matrix.platform != 'linux-s390x'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.recipe }}_${{ matrix.platform }}_run_id
          path: run_id.txt
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
          
      - name: Upload conda package
        if: github.event.inputs.run_stage == 'end' || matrix.platform != 'linux-s390x'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.recipe }}_${{ matrix.platform }}
          path: conda_channel_dir/*
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
          if-no-files-found: error
